myapp/urls.py
from django.urls import path
from myapp import views
from django.contrib.auth import views as auth_views
app_name="myapp"


urlpatterns=[
path('home/',views.home,name='home'),
path('register/',views.Registration,name='register'),
path('',auth_views.LoginView.as_view(template_name="myapp/login.html"),name="login"),
path('logout/',auth_views.LogoutView.as_view(template_name='myapp/logout.html'),name="logout"),
path('update/<id>/',views.update,name="update"),
path('delete/<id>/',views.delete,name='delete')
]

todoapp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models



class Todo(models.Model):
    event=models.CharField(max_length=20000,unique=True)
    time_added=models.DateTimeField(auto_now_add=True)
    time_updated=models.DateTimeField(auto_now=True)
    done=models.BooleanField(default=False)
    #event_time=models.DateTimeField()


    def __str__(self):
        return self.event

myapp/forms.py
from django import forms
from django.forms import ModelForm
from myapp.models import Todo


class TodoForm(ModelForm):
    class Meta:
        model=Todo
        fields=['event']
        #event_time=forms.DateTimeField(widget=forms.DateTimeInput(format='%m/%d/%y',attrs={'class':'datetimepicker'}),
        #input_formats=('%m/%d/%y'))
class DoneForm(ModelForm):
    class Meta:
        model=Todo
        fields=['done']

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from myapp.models import Todo
from myapp.forms import TodoForm,DoneForm
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    todo_obj=Todo.objects.all().order_by('-time_added','-time_updated')
    if request.method=="POST":
        todoform=TodoForm(request.POST or None, request.FILES or None)
        sucform=DoneForm(request.POST or None,request.FILES or None)
        if todoform.is_valid() and suform.is_valid():
            todoform.save(commit=True)
            todoform=TodoForm()
            sucform.save()
    else:
        todoform=TodoForm()
        sucform=DoneForm()
    context={
    'todo':todo_obj,
    'form':todoform,
    'sucform':sucform
    }
    return render(request,'myapp/home.html',context)
def Registration(request):
    if request.method=="POST":
        form=UserCreationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            obj=form.save(commit=False)
            obj.save()
            form=UserCreationForm()
    else:
        form=UserCreationForm()
    context={
    'form':form
    }
    return render(request,'myapp/register.html',context)
@login_required
def delete(request,id):
    instance=Todo.objects.get(id=id)
    instance.delete()
    return HttpResponseRedirect('/home/')
@login_required
def update(request,id):
    instance=Todo.objects.get(id=id)
    form=TodoForm(request.POST or None,instance=instance)
    if form.is_valid():
        instance.save()
        return HttpResponseRedirect('/home/')
    context={
    'form':form
    }
    return render(request,'myapp/update.html',context)

myapp/templates/myapp/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'myapp/style.css'%}">
    <title>Hello, world!</title>
    <nav class="navbar navbar-expand-md bg-steel fixed-top" style=background-color:black;>
    <div class="container">
      <a class="navbar-brand mr-4" href="/"><font size="6" face="chalkduster,georgia" style=color:white;>Daily To Do List.</font></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            {%if user.is_authenticated%}
            <a class="nav-item nav-link text-white" href="{%url 'myapp:home'%}">Home</a>
            {%endif%}
            </div>
            <div class="navbar-nav">
              {%if user.is_authenticated%}
              <a class="nav-item nav-link text-white" href="{%url 'myapp:logout'%}">Logout</a>
              {%else%}
              <a class="nav-item nav-link text-white" href="{%url 'myapp:login'%}">Login</a>
              <a class="nav-item nav-link text-white" href="{%url 'myapp:register'%}">Register</a>
              {%endif%}
              </div>
              </div>
              </div>
              </nav>
  </head>
  <body class="m-5 bg-light">
    <div class="container">
    {%block content%}
    {%endblock%}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

myapp/templates/myapp/delete.html
{%extends 'myapp/base.html'%}
{%block content%}


{%endblock%}

myapp/templates/myapp/home.html
{%extends 'myapp/base.html'%}
{%load icons%}
{%load crispy_forms_tags%}
{%block content%}
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-8">
<div class="card shadow-sm">
  <div class="card-header shadow-sm bg-muted">
<h1 class="display-5 text-info"><i class="fa fa-check p-2"></i>Todo List</h1>
    </div>
    <div class="card-body">


        <div class="row">
          <div class="col-sm-12">
            <table class="table table-striped table-bordered">
              <theader >
                <tr class="text-white" style=background-color:dodgerblue;>
                  <th>#</th>
                <th>Actity</th>
                <th>Time</th>
                <th>Done</th>
                <th>Operations</th>

                </tr>
                </theader>
                <tbody>
                  {%for todo in todo%}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{todo.event}}</td>
                    <td>{%if todo.done == False%}
                      <h3 class="text-danger"> <i class="fa fa-times fa-lg" aria-hidden='true'></i></h3>
                      {%else%}
                      <h3 class="text-success"><i class="fa fa-check fa-lg p-2"></i</h3>
                      {%endif%}
                    </td>
                    <td>
                      {%if todo.time_updated%}
                      {{todo.time_updated}}
                      {%else%}
                      {{todo.time_added}}
                      {%endif%}
                      </td>
                      <td>
                        <div class="input-group">
                        <a href="{%url 'myapp:delete' todo.id%}"><button class="btn btn-outline-danger m-1">Delete</button></a>
                      <a href="{%url 'myapp:update' todo.id%}"><button class="btn btn-outline-warning m-1">Update</button></a>
                      </div>
                    </td>

                    <tr>
                  {%endfor%}
            </tbody>

            </table>

        </div>

        </div>
      </div>
  </div>
  </div>
  <div class="col-sm-4 sticky-top">
  <div class=" card">
    <div class="card-header" style=background-color:dodgerblue;>
      <h5 class="display-5 text-white">Add Event</h5>
      </div>
    <div class="input-group col-sm-12">
      <form method="POST" action="" enctype="multipart/form-data">
        {%csrf_token%}
      {{form|crispy}}
      <button class="btn btn-outline-info btn-sm m-2"><i class="fa fa-plus-circle fa-lg text-dark"></i>Add</button>
      </form>
        </div>
    </div>
  </div>
</div>
{%endblock%}

myapp/templates/myapp/login.html
{%extends 'myapp/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="jumbotron">
<form method="POST" action="" enctype="multipart/form-data">
  <legend style=color:maroon;>Please Login</legend>
{%csrf_token%}
{{form|crispy}}
<button class="btn btn-outline-success">Sign In</button>
<br>
<a href="{%url 'myapp:login'%}"><small>forgot Password?</small></a>
  </form>
  </div>
{%endblock%}

myapp/templates/myapp/logout.html
{%extends 'myapp/base.html'%}
{%block content%}
<div class="jumbotron">
You have successfully been  logout.
<h3>Come Back Soon!!</h3>
<a href="{%url 'myapp:login'%}">Login Page</a>
  </div>
{%endblock%}

myapp/templates/myapp/register.html
{%extends 'myapp/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="jumbotron">
  <legend style=color:maroon;>Create An Account</legend>
  <hr>
<form method="POST" action="" enctype='multipart/form-data'>
{%csrf_token%}
{{form|crispy}}
<button class="btn btn-outline-success">Sign Up</button>
<br>
<small class="text-muted">Already have an account? </small><a href="{%url 'myapp:login'%}">Sign In</a>
  </form>
  </div>
{%endblock%}

myapp/templates/myapp/update.html
{%extends 'myapp/base.html'%}
{%block content%}
<div class="jumbotron">
<form method='POST' action="" enctype="multipart/form-data">
{%csrf_token%}
{{form}}
<button class="btn btn-success">Update</button>
  </form>
  </div>

{%endblock%}